// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0pspezF54yFtsU0HfUF7d2SNcswidIp4',
    appId: '1:120473900603:web:4c05a04b2747bfaacd6e1e',
    messagingSenderId: '120473900603',
    projectId: 'bookshop-flutter',
    authDomain: 'bookshop-flutter.firebaseapp.com',
    storageBucket: 'bookshop-flutter.firebasestorage.app',
    measurementId: 'G-K90NVCQDYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggfKGOg38zAtql6FmLc1qr1HlgFTVqc4',
    appId: '1:120473900603:android:d09162416db3901ecd6e1e',
    messagingSenderId: '120473900603',
    projectId: 'bookshop-flutter',
    storageBucket: 'bookshop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFMqXRKkfPUFvNOxupcfXmQ1WOBkAffXU',
    appId: '1:120473900603:ios:504e10cdef7b782bcd6e1e',
    messagingSenderId: '120473900603',
    projectId: 'bookshop-flutter',
    storageBucket: 'bookshop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.bookshopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFMqXRKkfPUFvNOxupcfXmQ1WOBkAffXU',
    appId: '1:120473900603:ios:504e10cdef7b782bcd6e1e',
    messagingSenderId: '120473900603',
    projectId: 'bookshop-flutter',
    storageBucket: 'bookshop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.bookshopFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0pspezF54yFtsU0HfUF7d2SNcswidIp4',
    appId: '1:120473900603:web:5ea7fbe66949d6b9cd6e1e',
    messagingSenderId: '120473900603',
    projectId: 'bookshop-flutter',
    authDomain: 'bookshop-flutter.firebaseapp.com',
    storageBucket: 'bookshop-flutter.firebasestorage.app',
    measurementId: 'G-4XZ8RJGD3J',
  );
}
